apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: renxox33/multi-worker
          env:
            - name: REDIST_HOST
              value: redis-cluster-ip-service
            - name: REDIST_PORT
              value: '6379'